<?php

$_dbstru = array(

'Cfg' =>
 "Module varchar(60) NOT NULL,
  Prop varchar(20) NOT NULL,
  Val text NOT NULL,
  UNIQUE KEY  (Module, Prop)",

'Hist' =>
 "hID int(10) NOT NULL auto_increment,
  hTS bigint(14) NOT NULL,
  hOper varchar(10) NOT NULL,
  huID int(10) default 0,
  hIP varchar(15),
  hcID int(2) default 0,
  hSum decimal(13,6) default 0,
  hParams text,
  hTag int(10) default 0,
  hMemo varchar(60),
  hoID int(10) default 0,
  PRIMARY KEY  (hID),
  KEY HTS (hTS),
  KEY HTAG (hTag,hMemo)",

'Users' =>
 "uID int(10) NOT NULL auto_increment,
  uGroup varchar(40) NOT NULL,
  uLogin varchar(40) NOT NULL,
  uPass varchar(32) NOT NULL,
  uPass2 varchar(32) NOT NULL,
  uMail varchar(60) NOT NULL,
  uPIN varchar(32) default '',
  uState int(1) default 0,
  uBTS bigint(14),
  uLevel int(2) default 0,
  uLang varchar(10) default 'en',
  uMode varchar(10) default '',
  uTheme varchar(10) default '',
  uRef int(10) default 0,
  uBal decimal(13,6) default 0,
  uLTS bigint(14),
  uLIP varchar(15),
  uLSess varchar(32),
  uPTS bigint(14) default 0,
  uBFC int(1) default 0,
  PRIMARY KEY  (uID),
  UNIQUE KEY ULOGIN (uLogin),
  UNIQUE KEY UMAIL (uMail),
  KEY UREF (uRef),
  KEY ULTS (uLTS)",

'AddInfo' =>
 "auID int(10) NOT NULL,
  aName varchar(60) NOT NULL,
  aCTS bigint(14) NOT NULL,
  aCIP varchar(15) NOT NULL,
  aSQuestion varchar(60),
  aSAnswer varchar(32),
  aPerc text,
  aDPerc text,
  aPPerc text,
  aIPSec int(1) default 0,
  aSessIP int(1) default 0,
  aSessUniq int(1) default 0,
  aTimeOut int(3) default 0,
  aOIDs text NOT NULL,
  aTZ int(4) default 0,
  aBD bigint(14) NOT NULL,
  aCountry varchar(40) NOT NULL,
  aCity varchar(60) NOT NULL,
  aTel varchar(20) NOT NULL,
  aDefCurr int(2) default 0,
  aNoMail int(1) default 0,
  aNeedReConfig int(1) default 1,
  PRIMARY KEY  (auID)",

'News' =>
 "nID int(5) NOT NULL auto_increment,
  nDBegin bigint(14) NOT NULL,
  nDEnd bigint(14) NOT NULL,
  nTS bigint(14) NOT NULL,
  nTopic varchar(1000) NOT NULL,
  nAnnounce text NOT NULL,
  nText text NOT NULL,
  nAttn int(1),
  PRIMARY KEY  (nID)",

'Currs' => // CID - Currency ID (see psys.php) -> Name, Curr
 "cID int(2) NOT NULL auto_increment,
  cDisabled int(1) default 1,
  cHidden int(1) default 0,
  cCID varchar(4) NOT NULL,
  cCurrID varchar(10) NOT NULL,
  cName varchar(120) NOT NULL,
  cCurr varchar(60) NOT NULL,
  cParams text,
  cParamsSCI text,
  cParamsAPI text,
  cNumDec int(1) default 0,
  cCASHINMode int(1) default 1,
  cCASHINMin decimal(13,6) default 0,
  cCASHINMax decimal(13,6) default 0,
  cCASHINInt int(1) default 0,
  cCASHINComis decimal(6,2) default 0,
  cCASHINComisMin decimal(13,6) default 00,
  cCASHINComisMax decimal(13,6) default 00,
  cCASHOUTMode int(1) default 0,
  cCASHOUTMin decimal(13,6) default 0,
  cCASHOUTMax decimal(13,6) default 0,
  cCASHOUTInt int(1) default 0,
  cCASHOUTComis decimal(6,2) default 0,
  cCASHOUTComisMin decimal(13,6) default 00,
  cCASHOUTComisMax decimal(13,6) default 00,
  cCASHOUTLimitPer int(3) default 0,
  cCASHOUTLimit decimal(13,6) default 0,
  cEXMode int(1) default 0,
  cEXOut decimal(10,6) default 0,
  cEXIn decimal(10,6) default 0,
  cEXMin decimal(13,6) default 0,
  cEXMax decimal(13,6) default 0,
  cEXInt int(1) default 0,
  cEXComis decimal(6,2) default 0,
  cEXComisMin decimal(13,6) default 00,
  cEXComisMax decimal(13,6) default 00,
  cTRMode int(1) default 0,
  cTRMin decimal(13,6) default 0,
  cTRMax decimal(13,6) default 0,
  cTRInt int(1) default 0,
  cTRComis decimal(6,2) default 0,
  cTRComisMin decimal(13,6) default 00,
  cTRComisMax decimal(13,6) default 00,
  cBUYMode int(1) default 0,
  cSELLMode int(1) default 0,
  cBUY2Mode int(1) default 0,
  cSELL2Mode int(1) default 0,
  cGIVEMode int(1) default 0,
  cTAKEMode int(1) default 0,
  cMTS bigint(14),
  PRIMARY KEY  (cID)", // cParams - IN (public) wallet, cParams2 - OUT (private) wallet

'Wallets' =>
 "wcID int(2) NOT NULL,
  wuID int(10) NOT NULL,
  wBal decimal(13,6) default 0,
  wLock decimal(13,6) default 0,
  wOut decimal(13,6) default 0,
  wParams text,
  wMTS bigint(14),
  PRIMARY KEY  (wcID,wuID)",
  
'Opers' =>
 "oID int(10) NOT NULL auto_increment,
  oCTS bigint(14),
  oATS bigint(14),
  ouID int(10),
  oOper varchar(10),
  ocID int(2),
  oSum decimal(13,6) default 0,
  oComis decimal(13,6) default 0,
  oParams text,
  oParams2 text,
  oBatch varchar(40),
  oTag varchar(60),
  oTS bigint(14),
  oState int(1) default 0,
  oPTS bigint(14) NOT NULL,
  oMemo varchar(120),
  oNTS bigint(14),
  PRIMARY KEY  (oID),
  KEY OBATCH (ocID,oBatch),
  KEY OTAG (oTag)", // oParams2 - additional parameters (for ex. deposit)
  
'Pages'=>
 "pID int(3) NOT NULL auto_increment,
  pHidden int(1) default 0,
  pDirect int(1) default 0,
  pTopic varchar(120),
  pText text,
  PRIMARY KEY  (pID)",

'Calend'=>
        "cID int(6) NOT NULL auto_increment,
         cTS bigint(14) NOT NULL,
         cYear int(4),
         cMonth int(2),
         cDay int(2),
         cType int(1),
         cPerc decimal(7,2) default 0,
         PRIMARY KEY  (cID),
         KEY CTS (cTS),
         KEY CDAY (cYear,cMonth,cDay)",
  
/*'Banners' =>
 "rID int(10) NOT NULL auto_increment,
  rDisabled int(1) default 1,
  rDBegin bigint(14) NOT NULL,
  rDEnd bigint(14) NOT NULL,
  rPlace int(4),
  rName varchar(120),
  rPictURL varchar(500),
  rGoURL varchar(500),
  rWeeks int(3),
  PRIMARY KEY  (rID)",*/
  
'Plans' =>
 "pID int(3) NOT NULL auto_increment,
  pHidden int(1) default 0,
  pNoCalc int(1) default 0,
  pGroup int(2) default 0,
  pGroupReq int(2) default 0,
  pMaxCount int(3) default 0,
  pName varchar(400) NOT NULL,
  pDescr varchar(1000) NOT NULL,
  pMin decimal(13,6) default 1.00,
  pMax decimal(13,6) default 0,
  pDays int(5) default 0,
  pWDays int(1) default 0,
  pPerc decimal(7,2) default 0,
  pCompndMin decimal(7,2) default 0,
  pCompndMax decimal(7,2) default 0,
  pPer int(6) default 0,
  pNPer int(5) NOT NULL,
  pReturn decimal(7,2) default 100.00,
  pMPer int(5) NOT NULL,
  pClPer int(5) NOT NULL,
  pClComis decimal(7,2) default 100.00,
  pBonus decimal(7,2) default 0,
  pEnAdd int(1) default 0,
  pMinAdd decimal(13,6) default 1.00,
  pDPerc text,
  pPPerc text,
  pPClndr int(1) default 0,
  pmndID int(10) default 0,
  pmndIDdone int(10) default 0,
  pmnPerc decimal(7,2) default 0,
  PRIMARY KEY  (pID)",

'Deps' =>
 "dID int(10) NOT NULL auto_increment,
  duID int(10) NOT NULL,
  dState int(1) default 0,
  dpID int(3) NOT NULL,
  dCTS bigint(14) NOT NULL,
  dETS bigint(14) NOT NULL,
  dcID int(2) NOT NULL,
  dZ0 decimal(13,6) default 0,
  dZD decimal(13,6) default 0,
  dCompnd decimal(7,2) default 0,
  dZC decimal(13,6) default 0,
  dNTS bigint(14) NOT NULL,
  dLTS bigint(14) NOT NULL,
  dZP decimal(13,6) default 0,
  dNPer int(5) default 0,
  PRIMARY KEY  (dID),
  KEY AUID (duID),
  KEY ACTS (dCTS)",

'Review' =>
 "oID int(10) NOT NULL auto_increment,
  oTS bigint(14) NOT NULL,
  ouID int(10) NOT NULL,
  oText text,
  oOrder int(3) default 0,
  oState int(1) default 0,
  PRIMARY KEY  (oID)",

'FAQ' =>
 "fID int(5) NOT NULL auto_increment,
  fHidden int(1) default 0,
  fCTS bigint(14) NOT NULL,
  fCat varchar(100) NOT NULL,
  fOrder int(3) NOT NULL,
  fQuestion varchar(2000) NOT NULL,
  fAnswer text NOT NULL,
  PRIMARY KEY  (fID)",

'Queue' =>
 "qID int(10) NOT NULL auto_increment,
  quID int(10) NOT NULL,
  qTS bigint(14) default NULL,
  qFrom varchar(11) default '',
  qTo varchar(30) default '',
  qaID int(10) NOT NULL,
  qText varchar(1600) default '',
  qxID int(10) NOT NULL,
  qTranslit int(1) default 0,
  qTest int(1) default 1,
  qKey varchar(32) default '',
  qState int(1) default 0,
  qSTS bigint(14) default 0,
  qParts int(2) default 0,
  qPrice decimal(13,6) default 0,
  qError varchar(100) default '',
  qErrCnt int(1) default 0,
  PRIMARY KEY  (qID),
  KEY QUID (quID),
  KEY QKEY (qKey)",
  
'Tickets' =>
 "tID int(10) NOT NULL auto_increment,
  tuID int(10) NOT NULL,
  tTS bigint(14) default NULL,
  tTID varchar(32) default '',
  tName varchar(60) default '',
  tMail varchar(60) default '',
  tCat varchar(100) default '',
  tTopic varchar(200),
  tText text,
  tPriority int(1),
  tState int(1),
  tLang varchar(10) default 'en',
  tLTS bigint(14),
  PRIMARY KEY  (tID),
  KEY TUID (tuID)",
  
'TMsg' =>
 "mID int(10) NOT NULL auto_increment,
  mtID int(10) NOT NULL,
  muID int(10) NOT NULL,
  mTS bigint(14) default NULL,
  mText text NOT NULL,
  mRTS bigint(14),
  PRIMARY KEY  (mID),
  KEY MTID (mtID)",

'Msg' =>
 "mID int(10) NOT NULL auto_increment,
  muID int(10) NOT NULL,
  mTS bigint(14) default NULL,
  mMail varchar(60) default '',
  mAttn int(1),
  mTopic varchar(120) default NULL,
  mText text NOT NULL,
  mLang varchar(10) default 'en',
  mGroup int(10) default 0,
  mTo text NOT NULL,
  mToCnt int(6) NOT NULL,
  PRIMARY KEY  (mID),
  KEY MUID (muID)",

'MBox' =>
 "bID int(10) NOT NULL auto_increment,
  buID int(10) NOT NULL,
  bmID int(10) NOT NULL,
  bRe int(10) default 0,
  buID2 int(10) NOT NULL,
  bMail varchar(60) default '',
  bRTS bigint(14) default NULL,
  bDeleted int(1) default 0,
  PRIMARY KEY  (bID),
  KEY BUID (buID),
  KEY BUID2 (buID2),
  KEY BMID (bmID)"

);